// this model can be autogenerated from backend
import {Card} from './Card/model'

export type Hand = HandDto

// --  from backend
export enum HandStatus {
  // Playing status
  Hit = "Hit",

  // Waiting dealer
  Stay = "Stay",
  BlackJack = "BlackJack",

  // final status
  Burst = "Burst",  // lose by Burst

  // final status via eval with dealer
  Win = "Win",      // normal win
  WinBlackJack = "WinBlackJack", // win by BlackJack
  Draw = "Draw",    // draw by same point or same blackjack
  Lose = "Lose",    // lose by lesser point
}
export type HandDto = {
  playerId?: string, // 1 player can have n hands
  handIdx: number;
  cards: Card[],
  status: HandStatus,
}
