// this model can be autogenerated from backend
import {Card} from './Card/model'

enum HandState {Burst, Stay, CanHit}
export type Hand = {
  cards: Card[]
}

// export class Hand {
//   cards: Card[] = []
  // addCard() {
  //
  // }
  // eval(): HandState {
  //   return HandState.CanHit
  // }
// }
